### ISSUE TITLE
在QQ和微信内置浏览器的问题

### ISSUE THREAD

**Issue by saymy** [YvesCoding/vuescroll#78]
在QQ和微信内置浏览器，打开之后：
1、滚动条不显示；
2、向上拉加载更多之后，不能再向上滚动；

建议：在移动端，6px宽滚动条是不是太宽了，能否像原生的滚动条一样。

**Comment by wangyi7099** [comment]
好的 我可以看看1 2

Ps。 滚动条宽度可以配置的。

**Comment by wangyi7099** [comment]
我在微信里打开官网 的 demo是可以的。
能否加个[微信交流群](https://vuescrolljs.yvescoding.org/zh/#%E5%BE%AE%E4%BF%A1%E4%BA%A4%E6%B5%81%E7%BE%A4)， 把地址发过来我打开看下

**Comment by saymy** [comment]
官方node环境下的demo，在我本运行出错：
> node server

fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\zouchunbo\Downloads\vuescroll-ssr-node-master\vuescroll-ssr-node-master\src\index.template.html'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at setupDevServer (C:\Users\zouchunbo\Downloads\vuescroll-ssr-node-master\vuescroll-ssr-node-master\build\setup-dev-server.js:41:17)    at Object.<anonymous> (C:\Users\***\vuescroll-ssr-node-master\server.js:35:53)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

另外，再次测试了一下，出现1，2情况，准确地说是在苹果手机里的，QQ和微信浏览器里。
我是苹果IOS12里的QQ和微信。

用安卓手机测试没有问题。
在钉钉内置浏览器和safari中打开没有问题。

**Comment by wangyi7099** [comment]
代码能否发下 我研究下
